openapi: 3.0.1
info:
  title: |
    Topic Extraction (Labs)
  contact:
    email: labs@rev.ai
    name: Rev
    url: 'https://www.rev.ai/'
  version: v1
  description: |
    # Quick Start
    Follow the [getting started checklist](https://www.rev.ai/getting_started). This feature is available in Labs for free through at least January 31st, 2022.
servers:
  - url: 'https://api.rev.ai'
    description: Rev AI API
security:
  - AccessToken: []
paths:
  /topic_extraction/v1/jobs:
    $ref: 'src/topicExtraction.yaml#/paths/~1jobs'
  /topic_extraction/v1/jobs/{id}:
    $ref: 'src/topicExtraction.yaml#/paths/~1jobs~1%7Bid%7D'
  /topic_extraction/v1/jobs/{id}/result:
    $ref: 'src/topicExtraction.yaml#/paths/~1jobs~1%7Bid%7D~1result'
components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
